alphagov/forms-product-page

source/index.html.erb

> Straight quotes are a typewriter habit. In traditional printing, all quotation marks were curly. But typewriter character sets were limited by mechanical constraints and physical space.
>
> […]
>
> Compared to straight quotes, curly quotes are more legible on the page and match the other characters better.
– https://practicaltypography.com/straight-and-curly-quotes.html
This commit replaces the use of a straight single quotation mark as an apostrophe with the typographically-correct equivalent.

Use typographic apostrophe on product page

---

source/features.html.erb

Added completed features:
- Draft of a live form functionality
- Autofill functionality for accessibility
Removed the above from future features and added in:
- questions you can answer more than once
- ability to make an account and trial the product
Trello:https://trello.com/c/u86TWxRb/671-update-features-page-on-product-site-autofill-and-draft-functionality

Add autofill and draft features

---

source/privacy.html.erb

Adding Google analytics to the product pages changes our cookie policy and privacy policy.
This commit updates the privacy policy to cover the use of analytics.
Trello: https://trello.com/c/GuNfSroW/880-update-privacy-policy-with-data-well-collect-if-you-consent-to-analytics
Because the [analytics branch](https://github.com/alphagov/forms-product-page/pull/29) can't be deployed without this change, this PR is merging into that one.

Update the privacy policy to cover analytics

---

config.rb
jest-puppeteer.config.mjs
source/_cookie_banner.html.erb
source/cookies.html.erb
source/javascripts/components/cookie_banner.mjs
source/javascripts/components/cookie_banner.test.mjs
source/javascripts/components/cookie_page.mjs
source/javascripts/components/cookie_page.test.mjs
source/javascripts/services/cookie.mjs
source/javascripts/services/cookie.test.mjs
source/javascripts/services/google_tag.mjs
source/javascripts/services/google_tag.test.mjs
source/javascripts/site.mjs
source/layouts/layout.erb
source/privacy.html.erb
tests/fixtures/cookie_banner.html
tests/fixtures/cookie_page.html
tests/functional/cookie_banner.test.mjs
tests/functional/cookie_page.test.mjs

[First trello card](https://trello.com/c/S3oafmnN/697-add-google-tag-to-the-product-pages)
[Second trello card](https://trello.com/c/BpmIEHIT/696-add-ga-consent-mechanism-to-the-product-pages)
[Copy document](https://docs.google.com/document/d/1oMUTedN38L484HQO7-PHI-dg79tDb-uzDrU2oXKQJoo/edit#heading=h.k3djl5u06erz)
This PR adds a consent mechanism - cookie banner and page and google tag manager to the product pages.
It's inspired by others work on these sites: 
- https://github.com/alphagov/govuk-design-system
- https://github.com/alphagov/govuk-developer-docs/commit/b11a8d32960496553b646427ccac693444cd69ce
The requirements stated that:
- we can't just relay on google analytics standard events, we must push events to the tag manager data layer following a set schema
- we shouldn't rely …

Add analytics

---

source/javascripts/services/cookie.mjs
source/javascripts/services/cookie.test.mjs
tests/functional/cookie_banner.test.mjs

Cookies are set with a path value which defaults to the current page. This meant that when consent was granted or denied on different pages, the cookie wasn't read on others.
This is fixed by setting the path to '/'. This is ok because the site is hosted on 'https://www.forms.service.gov.uk/'

Set consent-cookie path

---

.github/workflows/test.yml
app/frontend/entrypoints/application.js
app/frontend/javascript/components/cookie_banner.mjs
app/frontend/javascript/components/cookie_banner.test.mjs
app/frontend/javascript/components/cookie_page.mjs
app/frontend/javascript/components/cookie_page.test.mjs
app/frontend/javascript/services/cookie.mjs
app/frontend/javascript/services/cookie.test.mjs
app/frontend/javascript/services/google_tag.mjs
app/frontend/javascript/services/google_tag.test.mjs
app/views/layouts/application.html.erb
app/views/pages/_cookie_banner.html.erb
config/initializers/session_store.rb
jest-puppeteer.config.mjs
jest.config.mjs
package-lock.json
package.json
tests/fixtures/cookie_banner.html
tests/fixtures/cookie_page.html
tests/functional/cookie_banner.test.mjs
tests/functional/cookie_page.test.mjs
tests/functional/homepage.test.mjs

This is part of the continuing work to migrate the product pages to Rails. This PR contains the javascript used by the cookie banner and the consent form on the cookies page, pretty much unchanged from the Middleman version. It also contains associated Jest unit and functional tests, and the cookie banner partial itself.

Add javascript and cookie banner

---

Dockerfile

This is a first basic dockerfile for the product pages rails app - at the moment the app just has a ping endpoint, so we'll continue to add to this dockerfile as the app develops. 
To review this PR, in the root of `forms-product-page`:
- `docker build . -t rails_docker:1`
- `docker run -p 3000:3000 rails_docker:1`
- `curl http://localhost:3000/ping`
- you should see 'PONG' in return

add basic Dockerfile for rails

---

Dockerfile
Gemfile

Assets are not being built in the current Dockerfile, which results in errors at runtime about assets not being found.
To fix this, the rails assets:precompile command in the build section of the Dockerfile.
We also need to add `tzinfo` and `tzinfo-data` gems as alpine doesn't include these.
This matches forms-admin.
To check this fixes the issue, run:
```
docker build -t product-test .
docker run -e RAILS_LOG_TO_STDOUT=true -e RAILS_ENV=production -e RAILS_SERVE_STATIC_FILES=true -p 3007:3000 --rm product-test
```

Fix docker asset build

---

config/initializers/config.rb

Use the settings.yaml and set the separator as `__`.
Deployed this to dev and we've seen the exception come through to Sentry (note that the sentry settings were not being set because the initialisation of the settings gem was not configured correctly).

Align Configuration With Other Apps

---

config/puma.rb

This PR adds a persistent_time of 75 to the puma config so that it is higher than the ALB idle time as this was causing 502s

add persistent timout of 75 to puma

---

.github/workflows/test.yml

In preparation for merging `main-rails` into `main`, we need to make sure we'll run the GitHub actions appropriately on the main branch and for PRs into the main branch.

Run test workflow for main as well as main-rails

---

config/puma.rb

To avoid port collisions with the forms-admin app [[1]], change the default port from 3000 to 3002.
[1]: https://github.com/alphagov/forms-admin/blob/545be0398d190c29b4bacbec6ac4955864595b23/config/puma.rb#L18

Change default port

---

app/views/pages/privacy.erb

Update to cover personal information collected if you contact us. The privacy notice already covered contacting us by email, but now will also cover contacting us through the support form we plan to add to the product site. I have used the non specific language of 'contacting us' to cover both of these routes. 
I've also removed a line about cookies that we don't need on this page as we cover it in the cookies page. 
Trello: https://trello.com/c/ChYe4oVe/1030-review-and-update-the-privacy-policy-to-reflect-the-new-support-form
- Did Hannah do it all correctly? Let her know if not cos she wants to be better at github!

Update privacy notice for support form

---

app/helpers/application_helper.rb
app/views/layouts/application.html.erb
app/views/support/form.html.erb
app/views/support/support.html.erb
spec/helpers/application_helper_spec.rb

Trello card: https://trello.com/c/M1kGMpxU 
We've been discussing in our feature team the option of stopping our support page being indexed by search engines [[1]]; this is because members of the public often come across our page when searching for help with government services, but as a team we're only able to help with queries from people who want to build forms. This came up again recently when I was talking to GOV.UK Notify, who have done the same thing [[2]].
This PR adds a `noindex` robots directive to the support form pages, in the manner documented by Google [[3]] and also used by Notify [[2]].
If you're reviewing this change and feel like this is a bad idea, feel free to say so, either on here or on Slack :D
[1]: https://gds.slack.com/archives/C05P47JF05Q/p1695199556948639
[2]: …

Hide support form from search engines

---

README.md

We didn't have a URL for the Product Pages.

Update README.md to show where the Product Pages actually live

---

app/frontend/entrypoints/application.scss

Trello card: none
This message is appearing because ie8 support is deprecated in govuk-frontend. We don't support Internet Explorer 8 anyway, so we can suppress this warning.
Test this by running `bin/setup` or `bin/vite build` and observing that the FE build no longer gives us the following warning: 
> The govuk-if-ie8 mixin is deprecated and will be removed in v5.0. To silence this warning, update $govuk-suppressed-warnings with key: "ie8"
I've also made this change in forms-admin (https://github.com/alphagov/forms-admin/pull/688) and forms-runner (https://github.com/alphagov/forms-runner/pull/446) .
- Ensure that you consider the wider context.
- …

Suppress IE8 warning

---

app/views/pages/cookies.erb
app/views/pages/privacy.erb

We're switching to using Auth0 for authentication. They use cookies to make this work. They also get access to each user's email address. So we need to add some information about this to our cookies statement and privacy notice.
Not to be merged until we switch to Auth0.
Trello card: https://trello.com/c/HPTRv42o/839-draft-change-to-cookies-privacy-notice-to-include-auth0-cookies-and-data
- Did Hannah do everything right/well? Let her know if not!
- Are there any straight quotes that should be curly? 

Update cookies and privacy pages for Auth0

---

config/settings.yml

Trello card: 
In alphagov/forms-deploy#423 we added `SETTINGS__FORMS_ADMIN__BASE_URL` to the AWS environment variables for this app; this PR adds this config variable to `config/settings.yml` so we can access the value and have a sensible default if it is not set.
This PR pulls from the draft changes in #111 by @jamie-o-wilkinson, so I can use them before that PR is merged.

Add URL for forms-admin to settings

---

app/controllers/pages_controller.rb
app/views/pages/get_started.html.erb
config/routes.rb

Trello card: https://trello.com/c/4p6qkzvc/ 
We want a get started page explaining to users how to create an account and start using GOV.UK Forms. This PR adds the page designed by @hannahkc.
<details><summary><h3>Screenshot</h3></summary>
</details>

Add get started page

---

app/components/header_component/view.rb
app/views/layouts/application.html.erb
config/initializers/govuk_components.rb
config/locales/en.yml
spec/components/header_component/view_spec.rb
spec/rails_helper.rb

Trello card: https://trello.com/c/4p6qkzvc 
We want to change the header for the above ticket, and also for PR #111, I thought I'd take the opportunity to refactor the application.html.erb layout to use a view component instead of hardcoded HTML.
Following the examples from forms-admin and form-runner [[1], [2]], I've created a new view component that calls the `govuk_header` component from the `govuk_components` gem [[3]]. Unfortunately I couldn't just lift and shift the code from either app; for various reasons we've ended up with slightly different headers in each of our apps :sweat_smile:. I was able to re-use enough though that when we have time to consolidate it should be straight-forward to mash all the different implementations together.
Oh, also note that when I was doing this I …

Refactor header to use view component from `govuk_components` gem

---

app/views/layouts/application.html.erb
app/views/pages/index.html.erb
spec/views/layouts/application.html.erb_spec.rb

We want users who visit our product page to be able to sign up to GOV.UK Forms for a trial account, or sign in to their existing account.
This PR adds a link to sign in to forms-admin to the header navigation, and also directs new users to the new get started page (added in #116) from the home page call to action.
Trello card: https://trello.com/c/xebzfFm9, https://trello.com/c/4p6qkzvc
<details><summary>Screenshot</summary>
<p>
</p>
</details> 

Add sign in link and get started page to header navigation

---

app/views/pages/get_started.html.erb
spec/views/pages/get_started.html.erb_spec.rb

Trello card: https://trello.com/c/4p6qkzvc/1175-product-site-create-get-started-page-so-people-can-create-trial-accounts
This was missed in #116, the call to action on the get started page should point users to the 'Create an account' journey in forms-admin, rather than the 'Sign in' journey.

Redirect users to sign up route from get started page

---

config/initializers/govuk_components.rb
spec/components/header_component/view_spec.rb

govuk_components 4.1.2 was released with fixes for issues x-govuk/govuk-components#460 and x-govuk/govuk-components#461, and we're now using the version with the fixes in this app (see Dependabot PR #123), so we can remove our workaround and get our tests passing properly.

Remove workarounds for govuk_components header

---

app/views/pages/get_started.html.erb

Trello card: https://trello.com/c/iDUTqGVm/1223-update-product-page-content-for-users-from-organisations-which-may-restrict-their-access
Added a warning to set expectations that some people will not be able to create a trial account because their department is restricting access. 
Also:
- removed a line that was duplicative - so the page doesn't get too busy. 
- changed 'and preview your forms' to 'and see how it works' to avoid people thinking they'll be able to see their department's forms as a trial user and because it's less specific to one thing you can do.

Add warning to 'get started' page about department restrictions

---

app/views/pages/features.html.erb
app/views/pages/index.html.erb

Trello card:https://trello.com/c/R2dd3YMe/1211-update-the-wording-of-the-mailing-list-registration-page
As we have now launched GOV⁠.⁠UK Forms (Early Access), this updates a reference on the 'Features' page to getting a notification when GOV⁠.⁠UK Forms has launched, and to it being in development with selected government partners.
This also adds a link to the mailing list to the homepage - because the mailing list is no longer the main call to action on the homepage. 
- Did Hannah mess up the ruby links? or the spacing? 
- Does it look right and work right when run on your machine?

Update features and homepage content

---

config/application.rb
config/environments/production.rb

Otherwise every environment was getting debug output in the stdout. Also this is closer to how Rails is set up, which hopefully means we have less diversion to help with future upgrades.

Move stdout logging back to prod as the default

---

config/routes.rb
spec/requests/application_controller_spec.rb

rails 7.1 introduced a health check endpoint by default. This default endpoint is called `/up`. Instead of returning 200 with the body response of `PONG`, it will return 200 if the app is healthy and it will output a html page with the background color set to green. If there is an issue it will return 500 error and the html page will have a red background.
We will need to update our infrasture to use /up instead `/ping` and to check the response code instead of the response body of PONG
see https://github.com/rails/rails/blob/f481353150c100dbd944d5aa84f2480264cd723c/railties/lib/rails/health_controller.rb
Trello card: https://trello.com/c/J0l5SpeE/1417-use-rails-default-healthcheck-endpoint
- Do the commit …

add default rails healthcheck endpoint

---

app/controllers/application_controller.rb
app/lib/lograge/custom_options.rb
spec/requests/application_controller_spec.rb

We want to be able to correlate our Elastic Load Balancer logs with app logs. This is particularly useful when there is a `460` error because the client has closed the connection for taking too long.
This PR adds the `X-Amzn-Trace-Id` header [[1]] to our request logging.
[1]: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-request-tracing.html

Add AWS application load balancer trace ID to logs

---

package-lock.json

Bumps pac-resolver from 7.0.0 to 7.0.1.
- [Release notes](https://github.com/TooTallNate/proxy-agents/releases/tag/pac-resolver%407.0.1)
- [Changelog](https://github.com/TooTallNate/proxy-agents/blob/main/packages/pac-resolver/CHANGELOG.md)

Bump pac-resolver from 7.0.0 to 7.0.1

---

package.json

Trello card: https://trello.com/c/4WGWwZRU/1496-resolve-vite-deprecation-warning
The CommonJS build of Vite will no longer be supported as of v6. 
Fortunately none of the JS files in this repo are CommonJS anyway, so all we need to do to fix this is add `"type": "module"` to our package.json file.

Fix Vite CommonJS deprecation warning

---

app/views/pages/index.html.erb

Add home page link to new 'good forms' guidance in place of existing link to 'Use HTML, not PDF' blog post.
Trello card: https://trello.com/c/XgzbjxIM/454-add-links-to-new-make-good-forms-guidance-from-rest-of-product-pages
At the moment we're not linking to the new 'Good forms' guidance from anywhere. We'll want to build it into the information architecture when the sub-nav component is available. But for now, we'll link to it from the home page.
It's good to keep to 3 links if possible - and I've suggested removing the link to the 'Use HTML, not PDF' blog post - because we're already linking to it from the other blog post featured on the home page.

Add home page link to new 'good forms' guidance

---

public/humans.txt

Trello card: N/A
We temporarily added a message to the humans.txt file to shout out the team doing the assessment. We've now done the assessment (we passed!) so we can remove the message (we're still grateful to the people involved).

Remove beta assessment message from humans.txt

---

config/routes.rb

Trello card:[add-well-known-securitytxt](https://trello.com/c/SuTQEt4S/186-add-well-known-securitytxt)
This adds a  /.well-known/security.txt in line with[ the gds way](https://gds-way.digital.cabinet-office.gov.uk/standards/vulnerability-disclosure.html#vulnerability-disclosure), which helps people report vulnerabilities to cyber.
It does this by redirecting to alphagov's security.txt from `/security.txt.html` and `/.well-known/security.txt.html`
I have tested this locally, and we are redirected to the [security.txt](https://vdp.cabinetoffice.gov.uk/.well-known/security.txt) as expected when visiting the following urls:
- http://localhost:5100/.well-known/security.txt.html
- http://localhost:5100/security.txt.html
- Ensure that you consider the wider context.
- Does it work when run on …

Add  /.well-known/security.txt routes

---

app/views/pages/privacy.erb

There's a formatting problem with the paragraph starting 'This privacy notice explains what personal data the Cabinet Office collects from you, as someone using GOV.UK Forms ...'
I think it's because I omitted to wrap the paragraph in <p> </p> tags - this PR adds them.
But I can't run the app locally, so would be great if someone could do a visual check before merging.

Correct formatting error in privacy.erb

---

app/controllers/pages_controller.rb
app/views/layouts/application.html.erb
app/views/pages/_terms_of_use.html.erb
app/views/pages/terms_of_use.html.erb
config/locales/en.yml
config/routes.rb
spec/requests/pages_spec.rb
spec/views/layouts/application.html.erb_spec.rb
spec/views/pages/terms_of_use.html.erb_spec.rb

> [!WARNING]
> This PR should not be merged until the content has been reviewed, and the PR has been updated to use the agreed content.
Trello card: https://trello.com/c/hORT21Wv
This PR adds a terms of use page, which is linked to from the footer in forms-product-page. A subsequent PR in forms-admin will add a link to this terms of use page to the footer in forms-admin.
<details><summary>Screenshot</summary>
</details> 

Add terms of use page

---

app/frontend/entrypoints/application.scss
app/frontend/styles/_hero-alternative-action.scss
app/frontend/styles/_hero.scss
app/frontend/styles/_navigation.scss
app/frontend/styles/_related-items.scss
app/frontend/styles/_sub-navigation.scss

Trello card: https://trello.com/c/m5hB6sVM/2088-resolve-sass-mixed-declarations-deprecation-warning
Fixes a [deprecation warning](https://sass-lang.com/documentation/breaking-changes/mixed-decls/) related to the way that the sass declarations are ordered. In v2, the way these  declarations are turned into CSS will change and if they're left as they are they'll generate more CSS than is
necessary.
There shouldn't be any visual differences as a result of these changes. 

Fix Sass 'mixed declarations' warning

---

bin/thrust

This was added as part of the Rails 8 upgrade, but we don't need it as we don't use Thruster and are using NGINX.

Remove redundant thrust script

---

app/frontend/entrypoints/application.scss
vite.config.ts

Trello card: https://trello.com/c/pfzCTVnB/2066-investigate-asset-building-issue-with-modern-sass-api
We were seeing [an issue with assets failing to build properly using the 'modern' Sass API](https://trello.com/c/pfzCTVnB/2066-investigate-asset-building-issue-with-modern-sass-api). After investigating this appears to be caused by a bug in the Vite internal sass importer (https://github.com/vitejs/vite/issues/19196). 
This PR:
- uses the sass NodePackageImporter import govuk-frontend, which bypasses that bug and also offers us some other advantages (see commit message for more details)
- updates to use the modern API
- removes some redundant imports
- uses a more compact API for setting the asset paths
- Do …

Switch to modern Sass api

---

app/frontend/entrypoints/application.scss
app/frontend/styles/_borders.scss
app/frontend/styles/_breadcrumbs.scss
app/frontend/styles/_code-samples.scss
app/frontend/styles/_header.scss
app/frontend/styles/_hero-alternative-action.scss
app/frontend/styles/_hero.scss
app/frontend/styles/_inverted-button.scss
app/frontend/styles/_masthead.scss
app/frontend/styles/_navigation.scss
app/frontend/styles/_related-items.scss
app/frontend/styles/_responsive-embed.scss
app/frontend/styles/_sub-navigation.scss

Trello card: 
Sass has deprecated `@import` and replaced it with two new commands, `@use` and `@forward`.
`@use` allows importing something from another sass file (or a dependency) and using it in the current file.
`@forward` allows importing something from another sass file and 'forwarding' it along to any file that imports the current file.
`@import` puts everything from the file being imported into the global scope, and the new methods don't.  This means we have to update the way our Sass works a little bit. Previously if we did this:
```scss
// application.scss
$govuk-assets-path: "@govuk/assets/";
$govuk-global-styles: true;
@import "pkg:govuk-frontend";
@import "./borders";
```
We could use things defined in govuk-frontend directly inside our `_borders.scss` file like so:
```scss
// …
```

Resolve Sass deprecations

---

Gemfile.lock

Update the version of the URI gem to avoid:
https://www.cve.org/CVERecord?id=CVE-2025-27221
Trello card: 

Update URI Gem to 1.0.3

---

app/components/metrics_summary_component/_index.scss
app/components/metrics_summary_component/view.html.erb
app/components/metrics_summary_component/view.rb
app/controllers/pages_controller.rb
app/controllers/performance_controller.rb
app/frontend/entrypoints/application.scss
app/views/pages/index.html.erb
app/views/pages/terms_of_use.html.erb
app/views/partials/_performance_metrics.html.erb
app/views/performance/index.html.erb
config/locales/en.yml
config/performance_metrics.yml
config/routes.rb
spec/components/metrics_summary_component/metrics_summary_component_preview.rb
spec/components/metrics_summary_component/view_spec.rb
spec/requests/performance_spec.rb

Trello card: https://trello.com/c/4HM3T6Na/2118-create-initial-performance-page-in-product-pages
Adds a new page/partial for the performance data we want to highlight.

Add Performance metrics page

---

spec/features/support_form_spec.rb

Trello card: 
We're seeing an issue where it appears that Capybara isn't waiting for the page navigation to complete before checking the URL, resulting in a wrongly failing test.
For some matchers, such as have_text, Capybara waits for the text to become available. That wait logic still appears to be working correctly.
This commit switches the order of our have_text and current_url assertions, so that the current_url assertion benefits from have_text matcher's wait logic.

Add workaround for capybara failure

---

app/components/service_navigation_component/_index.scss

Trello card: https://trello.com/c/xGYhUwWH/2206-update-the-navigation-on-the-govuk-forms-product-page
Styling tweak to #722 so that the right-alignment only applies at tablet width or wider.

Fix alignment for sign in link on small screens

---

app/views/pages/features.html.erb
app/views/pages/forthcoming_features.html.erb

Trello card: https://trello.com/b/9cKfKKdR/govuk-forms-sprint-board
Updates to features and forthcoming features pages to include branching.
**Features page**
- Edited the existing ‘Set questions to skip’ section. Gave it a new heading: ‘Add a route to skip questions based on a specific answer’.
- Added a new section explaining 2-route branching, under the heading ‘Add a second route to create 2 ‘branches’ of questions’
See [Google doc for track changes to features page](https://docs.google.com/document/d/10TEpn9dbAnEGm97KxINgQCYD0rzijmwLT48K7V49YkA/edit?pli=1&tab=t.3sls1utzi4e4)
**Forthcoming features page**
- Removed branching as we’re releasing it
- Moved Welsh form components up to ‘What we're working on now’
- Changed heading from 'What we plan to work on in 2025' to ‘Later in 2025’ …

[DO NOT MERGE YET] Branching updates to product pages

---

app/services/feature_service.rb
config/settings.yml
config/settings/development.yml
spec/services/feature_service_spec.rb

To manage the rollout of the GOV.UK Rebrand, we're adding a feature flag to this app to help.
We also add a FeatureService which is lifted from Runner. If we don't need feature flags for Product in future we can delete it entirely.
See also: https://github.com/alphagov/forms-runner/pull/1397 
Trello card: https://trello.com/c/ROAXJEiF/2860-add-feature-flags-to-product-pages-and-runner-for-rebranding 

Add feature flag for rebrand

---

Dockerfile

Trello card: https://trello.com/c/KoHvaEUA/681-aws-m112-ecs-read-only-root-filesystem-configuration
Previously we created 1 volume for each directory that the application needed to write to, because we found it didn't have permission to create subdirectories of a volume.
This is because we weren't doing it correctly. The correct way to do it is to create the directory in the Dockerfile and set its permissions and owner, then expose it as a volume.

Create volumes for whole directories in the Dockerfile

---

app/views/pages/features.html.markerb
app/views/pages/forthcoming_features.html.markerb

Trello card: [Prepare comms for releasing exit pages](https://trello.com/c/lYK3tSvx/2263-prepare-comms-for-releasing-exit-pages?filter=label:Feature%20team%20two)
Updates to both the features page ['How GOV.UK Forms works'](https://www.forms.service.gov.uk/features) and ['Forthcoming features' page](https://www.forms.service.gov.uk/forthcoming-features)
- Added a new exit pages section
- Added mention of exit pages to the 'Add a route to skip questions based on a specific answer' section
- Removed the word 'simplest' from intro line of the 'Features available now' section
See ['Features page updates']( https://docs.google.com/document/d/10TEpn9dbAnEGm97KxINgQCYD0rzijmwLT48K7V49YkA/edit?pli=1&tab=t.30ekdtqhocfp)doc for tracked changes 
- Removed mention of exit pages under 'What we're …

Features and forthcoming features page updates (June) - product site

---

app/components/header_component/view.rb
app/views/pages/features.html.markerb
spec/components/header_component/view_spec.rb

Trello card: https://trello.com/c/qBeUKH2I/2320-remove-beta-from-header-as-part-of-rebrand-on-product-pages
After the rebrand, the phase tag causes the product name to reflow to the next line on mobile displays with a small viewport (320px). Notify did some research on this and found that it didn't mean much to users so decided to follow suit.
As we've removed the beta tag, add some additional content about being in public beta.

Remove beta tag

---

config/locales/en.yml

Trello card: 
Changes the link text from 'Accessibility' to 'Accessibility statement', in order to make the target of the link more explicit and be consistent with the admin and runner footers.

Change accessibility statement footer link text

---

config/vite.json

Currently the vite build outputs to public/vite/assets. This doesn't match the runner and admin configuration which outputs them to public/assets.
This doesn't matter on it's own but it's a bit confusing to have them in different places.
If we wanted to apply caching at the CDN level, it's easier if they are in a standard location.
This commit aligns the configuration with the runner and admin by putting them in /public/assets.
There shouldn't be any changes to build or how the site works.
Trello card: 
- Has all relevant documentation been …

Move vite assets to /assets

---

app/views/support/support.html.erb

This updates the status page URL to use our custom URL (https://status.forms.service.gov.uk).

Update the status page URL to custom domain

---

app/markdown/erb_markdown.rb

When running locally, where ViewComponents are used, HTML comments were being added with the path of the component file. The Markdown generator was converting the `--` in the comments into em dashes, causing the comments to be rendered as text.
Strip out all HTML comments before rendering the Markdown to avoid this issue.

Strip all HTML comments from input before rendering Markdown
