- package.json
- source/index.html.erb
Fixes a typo in the content and an issue with the assets being copied to the wrong folder.
> Fix small issues in product page

- CONTRIBUTING.md
- LICENSE
- README.md
This shouldn't be merged until #4 has, or the instructions in README won't make sense. I've largely copied these from the forms-admin repo.
> Add CONTRIBUTING, LICENSE and README files

- source/cookies.html.erb
- source/layouts/layout.erb
- source/privacy.html.erb
Adds a cookie page, and links to that page in the footer. Some of the content isn't finalised, so may change, but functionally this should be complete.
Trello card: https://trello.com/c/wLbTy34H/55-draft-and-publish-cookie-information-to-cover-the-product-product-pages-and-forms
- [n/a] I've written unit tests for these changes (if code change)
- [n/a] I've updated the documentation in (If any documentation requires updating)
- [n/a] README.md
- [n/a] Elsewhere (please link)
> Add cookie page

- source/cookies.html.erb
- source/privacy.html.erb
Adds the latest cookie and privacy information to the product pages.
Trello cards:
https://trello.com/c/RRvlcejo/30-get-updated-content-for-the-govuk-forms-privacy-notice-drafted-and-approved
https://trello.com/c/wLbTy34H/55-draft-and-publish-cookie-information-to-cover-the-product-product-pages-and-forms
> Cookies and privacy content updates

- .github/workflows/deploy.yml
Adds a new workflow to deploy to the PaaS dev environment on merges to `main`.
Trello card: https://trello.com/c/yuE5jTzu/182-create-dev-and-staging-environments-for-forms-product-pages
> Add automated deployment

- .gitignore
- config.rb
- package.json
- source/features.html.erb
- source/index.html.erb
- source/javascripts/site.js
- source/layouts/layout.erb
- yarn.lock
Adds a 'features' page to the product page, and a couple of links to it from the other pages.
Previewable on staging: https://forms-product-pages-staging.london.cloudapps.digital/features/
> Add features page

- source/features.html.erb
Added: 
- declaration
- long text answer
- number answer
- optional questions
> Adding new features

- source/index.html.erb
Made this more representative of all the security stuff we're doing. Also, previously it could have been misinterpreted.
> Update 'secure' description

- source/index.html.erb
- source/layouts/layout.erb
- source/support.html.erb
Adds a support page to the site which directs people to our team email inbox. Adds a link to this page in the header and updates one of the homepage links to point to it.
Changes visible on staging here: https://forms-product-pages-staging.london.cloudapps.digital/support/
Trello card: https://trello.com/c/E9RdN98l/287-make-a-support-page-for-the-product-site-with-our-email-address-nice-to-have
> Add support page

- source/support.html.erb
Making the sub heading more general so it's clearer that it for questions as well as support.
> Content tweak to h2

- source/features.html.erb
Added selection questions as a new feature. 
Updated 'Features we're working on next' to align with our new roadmap.
A couple of other tweaks for readability.
> Update features page

- source/index.html.erb
Updated the line about the product being free - it's now free regardless of the number of expected transactions.
Trello: https://trello.com/c/HPzR8xfo/749-update-free-messaging-on-the-product-site
Also fixed a straight quote.
> Say that it's free

- app/controllers/heartbeat_controller.rb
- config/routes.rb
- spec/requests/heartbeat_controller_spec.rb
Add ping endpoints so we can check container health in ECS.
> Add basic /ping route

- app/controllers/pages_controller.rb
- app/views/pages/index.html.erb
- config/routes.rb
- spec/requests/pages_spec.rb
Add a controller, view and route for a simple index page.
The pages controller will be used for all the pages within the current
middleman project.
The next PR will be to add the fontend build and style the example
content with GOV.UK.
>  Add pages controller, view, route

- app/views/layouts/application.html.erb
Add missing GOV.UK icons, as per forms-admin.
> Add missing icons

- Gemfile.lock
- app/views/pages/accessibility.html.erb
- app/views/pages/privacy.erb
Merged privacy and accessibility content updates from main, via a 3rd branch to resolve conflicts. 
This includes some privacy page content changes made by @hannahkc, accessibility page content changes from @cmcnallygds and @hannahkc, and removal of the CODEOWNERS file by @jamie-o-wilkinson. I've also updated the Gemfile.lock as it was out of sync with the Gemfile.
I've left the merge commits as this history is already on the main branch.
> Merge main into main-rails

- app/frontend/styles/_inverted-button.scss
- app/views/pages/index.html.erb
Fixes issue raised in https://github.com/alphagov/forms-product-page/issues/11 
> Remove inverted button focus underline and add missing data-module attribute

- app/views/pages/features.html.erb
Added brief info about detailed guidance to 'Features available now' and removed it from 'Features we're working on next'.
Updated 'Features we're working on next' to include a metrics dashboard and confirmation email when someone's submitted a form. Moved tabular questions to the bottom of this list to reflect changing road map priorities.
Need to update features page of product site so that it's accurate
- Any typos or grammatical errors?
> Updates to features page.html.erb

- app/views/pages/index.html.erb
Have updated the information about what metrics users can see now the basic metrics dashboard is live
Need to update the homepage for accuracy.
Have changed the information under 'See how well your forms are working' so it reflects what's possible with the new basic metrics dashboard
- Does the change make sense and read correctly?
> Update index.html.erb - changed metrics information

- app/views/pages/features.html.erb
- app/views/pages/index.html.erb
- app/views/pages/privacy.erb
- config/routes.rb
- spec/requests/mailing_list_spec.rb
Add a route to redirect users to our mailing list page, which is hosted externally, for now. This saves us having to manage the URL in multiple places.
> Add path to subscribe to mailing list

- app/views/pages/features.html.erb
- app/views/pages/forthcoming_features.html.erb
- config/routes.rb
Created a new 'Forthcoming features' page. This will be a sub page of the existing features page. 
Trello card: https://trello.com/c/naT72SOD/1314-product-site-create-new-roadmap-page-and-navigation-for-product-site
- Has Hannah done anything wrong?  
> Create 'forthcoming features' page

- app/controllers/application_controller.rb
- app/lib/lograge/custom_options.rb
- config/application.rb
- config/environments/production.rb
- spec/controllers/application_controller_spec.rb
- spec/lib/lograge/custom_options_spec.rb
Rails' log_tag feature interferes with the log_rage JSON formatting, resulting in `[log_tags] {log_rage}` format. Since log_rage includes the request_id and anything else that log_tags could include we are not using log_tags in our application logging.
This also updates the log_rage configuration to add additional fields as per our other apps' configuration.
Trello: https://trello.com/c/dpoVXgXj/1361-fix-product-page-log-formatting
Makes produce-pages logging consistent with other apps. Improves the formatting for better searching and filtering within Splunk.
Original log format:
```
I, [2023-12-05T08:57:38.265725 #1]  INFO -- : [2d913798-3786-4b45-b6c0-6eab5a4c2f4e] {"method":"GET","path":"/ping","format":"html","controller":"HeartbeatController","action":"ping","status":200,"allocations" …
```
> Remove log tags

- app/views/pages/privacy.erb
Trello card:https://trello.com/c/2LkEGGto/1288-help-update-dpia-to-include-mailchimp-and-small-update-to-privacy-notice
This updates a reference to the mailing list to make it more accurate. 
And adds a line about the legal basis for collecting data for the mailing list.
> Update privacy notice

- .github/workflows/docker_build.yml
This was copied from forms-admin so it should match our other repos. You can also see that this PR does three checks (which includes checking if docker image can be built) compared to other PR which only do two checks.
Trello card: 
> add a check that docker image can be built to all PRs

- Gemfile.lock
> add darwin-23 to platforms in gemfile.lock

- README.md
This is supposed to do precisely nothing at all. It's only here so I can merge something into `main` and watch for the whole process roll through.
> A small, meaningless change used to test the path to production

- public/favicon.ico
Trello card: https://trello.com/c/j3LGb3mn/1375-blocked-on-tudor-crown-investigate-favicon-404-errors-in-production 
We're seeing a lot of `404`s in our server logs from clients trying to reach `/favicon.ico`. This PR hopefully will reduce those log messages by making it so we can serve the favicon from that path.
If poeople like this change I will roll it out the other apps.
I've tested this change in dev.
> Add favicon to server root as symlink

- public/humans.txt
Trello card: https://trello.com/c/ttBTyEDX/1546-add-a-humanstxt-file
Adds a [humans.txt](https://humanstxt.org/) file. Format shamelessly copied from the [GOV.UK](https://www.gov.uk/humans.txt) and [GOV.UK Pay](https://www.payments.service.gov.uk/humans.txt) implementations.
> Add humans.txt file

- app/views/pages/features.html.erb
- app/views/pages/forthcoming_features.html.erb
Trello card: https://trello.com/c/2z8v50U4/1436-comms-to-explain-the-new-add-a-payment-link-and-automatic-reference-number-functionality-to-users
Payment has now been released so this adds it to the main features page and removes it from the 'forthcoming features' page. 
> Add payment to 'features' page

- Gemfile
- Gemfile.lock
- lib/tasks/pause_pipelines.rake
Trello card: https://trello.com/c/HFSmspAf/381-automatically-deploy-to-dev-environments-after-production
The format is `rake pipelines:ENV:{pause,unpause,status}`.
> Introduce Rake tasks for pausing, unpausing, and getting the status of pipelines

- app/views/pages/forthcoming_features.html.erb
Removing an accidentally duplicated line.
Trello card: https://trello.com/c/uDmMECGo/1917-remove-duplicate-content-on-govuk-forms-forthcoming-features-page
- Are there any errors/typos in this change
> Remove duplicative line from forthcoming_features.html.erb

- app/views/pages/features.html.erb
- app/views/pages/forthcoming_features.html.erb
- app/views/pages/get_started.html.erb
- app/views/pages/index.html.erb
- spec/views/pages/get_started.html.erb_spec.rb
It updates content on the product site and changes the call to action on the homepage, ready for user management changes. 
Trello cards: 
https://trello.com/c/AfUfDHkk/1594-update-product-site-content-for-new-journey-to-try-out-and-start-using-govuk-forms-public-beta
https://trello.com/c/gcU2Ctxr/1601-product-site-update-features-and-forthcoming-features-pages-for-release-of-groups-features
I've changed a lot of content on the Get started page and it's the first time I've used github in ages!
- Does it look like I broke anything?
- Are there any typos?
- Are there any straight quotes?
> Update content for user management changes

- app/views/pages/forthcoming_features.html.erb
We know we're working on alternative submission methods and 'add another answer' next, so separating that out into a new section for specificity.
Trello card: https://trello.com/c/9Jnn7IfU/1628-small-update-of-the-forthcoming-features-page?filter=member:hannahcontenting
- Did hannah leave any duplicate content in?
- is the html all good? 
- are there any straight quotes?
> Update forthcoming features page

- package.json
Otherwise it waits for user to enter q to quit.
Similar to https://github.com/vitest-dev/vitest/issues/719 
Trello card: 
> Fix vitest waiting for file change

- app/views/support/support.html.erb
Updating support page to reflect the support we'll be offering from 6 August.
Trello card:https://trello.com/c/oJxwqSGY/1682-do-not-publish-till-6-august-update-support-information-on-the-product-site-for-public-beta?filter=member:hannahcontenting
Updating the information on the support form/page to reflect the support we'll be offering from 6 August. 
I have not run this locally sp please check it carefully. Also not sure what the right syntax is for a link in a html.erb file so please check that carefully too. 
> Update support page

- Gemfile.lock
Security audit was failing for webrick 1.8.1, which is a transitive dependency. This PR bumps it to 1.8.2, which passes security audit.
> Update webrick to 1.8.2

- app/views/pages/forthcoming_features.html.erb
Updating features page to include CSV files and add another answer content. 
Trello card: https://trello.com/c/MIvRjJXT/1828-3-comms-for-add-another-answer-and-csvs-of-completed-forms-features
> Update forthcoming_features.html.erb following launch of new features

- .gitignore
- Gemfile
- Gemfile.lock
- spec/spec_helper.rb
Trello card: 
Adds the simplecov gem to give us information about our test coverage. Uses the same configuration as we've got in admin/api/runner.
> Add simplecov for code coverage

- app/controllers/concerns/performance_data.rb
- app/controllers/pages_controller.rb
- app/controllers/performance_controller.rb
- config/performance_metrics.yml
- spec/features/support_form_spec.rb
Using the modified date on the file gave a false number when the app is redeployed. Also abstracted the fetching into a method shared across the controllers as a concern (which seems to be an appropriate application).
> Fix update date for performance metrics

- app/views/pages/features.html.erb
- app/views/pages/forthcoming_features.html.erb
Trello card: https://trello.com/c/0EA6BrNQ/2169-new-feature-launch-file-upload
Content updates to the features page to include file upload and the forthcoming features page to reflect our roadmap. 
> Update product site with file upload content

- .github/workflows/test.yml
- Gemfile
- Gemfile.lock
- package-lock.json
- package.json
Combines PRs
- #754
- #755
- #757
- #758
- #759
- #760
> Batch dependency updates

- .gitignore
Removes unnecessary boilerplate and unused files.
> Remove unnecessary .keep files from various directories

- app/views/pages/get_started.html.markerb
These are a few small changes to make the process for making forms live clearer.  
Trello card: https://trello.com/c/WkChrHhk/2215-blocked-while-we-wait-for-implementation-and-new-markdown-thing-tweak-content-to-make-it-clearer-that-form-creators-should-get-i
> Update get_started content

- app/views/pages/accessibility.html.md
This updates the accessibility statement to: 
- remove issues that have been fixed
- update the date we aim to fix one remaining issue
- update the reviewed and updated date of the statement
Trello card: https://trello.com/c/kvFF6LEl/2453-update-accessibility-statements-to-remove-content-referring-to-2024
> Update accessibility statement

- app/views/pages/privacy.html.md
Trello card:https://trello.com/c/LjtwzSY9
This adds an additional legal basis for processing data to the privacy notice - to cover when people consent to get an email about taking part in user research.
> Update privacy notice for UR email consent
